/**
 * PASAbi UI strings — EN / FIL. Source of truth for wording: docs/design/SCREENS.md.
 *
 * Rules (DESIGN_BRIEF.md §9, PRD BR-017):
 *  - Caveats are CONSTANTS here. Screens import them; they never write their own version.
 *  - Never add: successfully, please, just, oops, "!", verified, confirmed, safe (outside "I'm safe"),
 *    severity, danger. `scripts/check-copy` in IMPLEMENTATION.md greps for these.
 *  - Filipino is a first draft ⚑ — have a native speaker on the team pass it before the demo.
 *
 * If your app already has an i18n file, merge these keys into it instead of keeping two sources.
 */
export type Lang = 'en' | 'fil';

const en = {
  // Status band
  'band.offline': 'Offline · reports stay on this phone',
  'band.online': 'Online',
  'band.station': 'Station · {name}',
  'band.offline.station': 'Offline · local data only',
  'band.online.station': 'Online · uploaded {time}',
  'band.responder': 'Responder view · last sync {time}',
  'band.sim': 'Simulation · proof of protocol, not radios',
  'band.storage': '· storage almost full',

  // Home
  'home.count': 'reports on this phone',
  'home.countEmpty': 'Nothing on this phone yet',
  'home.urgent': '{n} urgent',
  'home.last': 'Your last report',
  'home.rateLimit': '6 reports this hour. Try again at {time}.',
  'action.report': 'Report',
  'action.report.sub': "What's happening?",
  'action.passOn': 'Pass on',
  'action.receive': 'Receive',
  'action.safe': "I'm safe",

  // Report flow
  'report.q1': "What's happening?",
  'report.q2': 'How many need help?',
  'report.notSure': 'Not sure',
  'report.q3': 'What did you see?',
  'report.q3.ph': 'e.g. Water above the road near the chapel',
  'report.q4': 'Where?',
  'report.gps.ok': 'Location found',
  'report.gps.none': 'Location not found',
  'report.landmark': 'Purok or landmark',
  'report.landmark.optional': 'Landmark (optional)',
  'report.next': 'Next',
  'report.save': 'Save report',
  'nav.back': 'Back',

  // Categories (BR-001)
  'cat.MEDICAL': 'Medical',
  'cat.TRAPPED': 'Trapped',
  'cat.STRUCTURAL': 'Damage',
  'cat.FLOOD': 'Flood',
  'cat.ROAD_BLOCKED': 'Road blocked',
  'cat.MISSING_PERSON': 'Missing person',
  'cat.WATER_FOOD': 'Water & food',
  'cat.SHELTER': 'Shelter',
  'cat.SAFE_CHECKIN': "I'm safe",

  // Slip + stamps (BR-015)
  'slip.status.saved': 'Saved on this phone only.',
  'slip.status.passed': 'Passed to another phone.',
  'slip.status.station': 'Reached a station.',
  'slip.status.uploaded': 'Uploaded from this phone.',
  'slip.grouped': 'Grouped with reports from {n} other phones.',
  'stamp.saved': 'Saved',
  'stamp.passed': 'Passed on',
  'stamp.station': 'At station',
  'stamp.uploaded': 'Uploaded',
  'stamp.ack': 'Ack {time}',
  'stamp.acknowledged': 'Acknowledged',
  'stamp.resolved': 'Resolved',
  'action.passItOn': 'Pass it on',
  'action.done': 'Done',

  // Pass on / receive
  'pass.title': 'Pass on',
  'pass.hint': 'Hold this up to the other phone.',
  'pass.batch': 'Batch {i} of {n} · {count} reports',
  'pass.pause': 'Pause',
  'pass.resume': 'Resume',
  'pass.next': 'Next batch',
  'pass.scanReceipt': 'Scan their receipt',
  'pass.swap': 'Swap roles to get theirs.',
  'pass.done': 'Passed on {n}',
  'pass.empty': 'Nothing on this phone to pass on.',
  'recv.aim': 'Point at their code.',
  'recv.progress': 'Hold steady · {i} of {n}',
  'recv.got': 'Got {n}',
  'recv.new': '{m} new',
  'recv.showReceipt': 'Show receipt',
  'recv.receiptHint': 'Let them scan this.',
  'err.cantRead': "Can't read it. Tilt away from light.",
  'err.cantRead.2': "Can't read it. Move the phones apart a little.",
  'err.cantRead.3': "Can't read it. Keep the code inside the frame.",
  'err.camera': 'Camera is off for PASAbi.',
  'err.openSettings': 'Open Settings',

  // My reports
  'mine.tab': 'Mine',
  'carrying.tab': 'Carrying',
  'mine.empty': 'Nothing reported yet.',
  'delete.q': 'Delete from this phone?',
  'delete.body': 'Copies already passed on stay.',
  'delete.yes': 'Delete',
  'delete.no': 'Keep',
  'undo': 'Undo',

  // Settings
  'settings.language': 'Language',
  'settings.saves': 'What PASAbi saves',
  'settings.saves.what': 'What you report',
  'settings.saves.where': 'Location, if found',
  'settings.saves.when': 'Time',
  'settings.saves.noName': 'Not your name',
  'settings.saves.noNumber': 'Not your number',
  'settings.saves.noAccount': 'No account',
  'settings.station': 'Station mode',
  'pin.wrong': 'Wrong PIN',
  'safe.title': "Tell the barangay you're safe.",
  'safe.go': 'Check in',

  // Station ledger (evidence strings use a no-break space so a number never wraps away from its word)
  'ledger.title': 'Situation',
  'ledger.counts': '{open} open · {resolved} resolved',
  'ledger.lastUpdate': 'Last update here',
  'ledger.sort': 'By priority',
  'ledger.markSeen': 'Mark seen',
  'ledger.empty': 'No reports yet.',
  'ledger.allOld': 'Everything here is over 3 hours old.',
  'mark.new': 'New',
  'mark.phone': '+1 phone',
  'mark.people': 'More people',
  'mark.reopened': 'Reopened',
  'fresh.fresh': 'fresh',
  'fresh.aging': 'aging',
  'fresh.stale': 'old',
  'old.note': 'May have changed.',
  'ev.phones': '{n}\u00A0phones',
  'ev.phone': '1\u00A0phone',
  'ev.reports': '{n}\u00A0reports',
  'ev.report': '1\u00A0report',
  'ev.people': '{n}\u00A0people',
  'cov.title': 'Coverage',
  'cov.high': 'Many phones',
  'cov.limited': 'Few phones',
  'cov.stale': 'Quiet since {time}',
  'cov.none': 'No reports',
  'cov.unnamed': 'No area named',

  // Incident
  'inc.back': 'Ledger',
  'inc.rank': '{ordinal} of {n} open',
  'inc.status.open': 'Open · not acknowledged',
  'inc.status.acked': 'Open · acknowledged',
  'inc.status.resolved': 'Resolved {time}. A new report reopens it.',
  'inc.phones': 'phones',
  'inc.reports': 'reports',
  'fact.lastHeard': 'Last heard',
  'fact.firstHeard': 'First heard',
  'fact.freshness': 'Freshness',
  'fact.people': 'People',
  'fact.people.value': '{n} in latest report',
  'fact.people.none': 'Not reported',
  'fact.spread': 'Spread',
  'fact.spread.value': 'Within {m} m',
  'why.title': 'Why {ordinal}?',
  'why.total': 'Total',
  'gap.nearby': 'Reported nearby',
  'gap.unheard': "Haven't heard about",
  'log.title': 'Log',
  'log.reported': '{src} reported',
  'log.reportedAgain': '{src} reported again',
  'log.received': 'Received at this station',
  'log.carriedBy': 'Carried by {src}',
  'log.acked': 'Acknowledged here',
  'log.resolved': 'Resolved here',
  'action.ack': 'Acknowledge',
  'action.resolve': 'Resolve',
  'undo.resolved': 'Resolved.',

  // Station
  'station.held': 'reports held',
  'station.storage': '{n} of {max}',
  'station.lastUpload': 'Last upload',
  'station.upload': 'Upload now',
  'station.needsNet': 'Needs internet.',
  'station.uploadFailed': 'Not uploaded. Still on this phone.',
  'station.retry': 'Try again',
  'station.leave': 'Leave station mode',
  'tab.ledger': 'Ledger',
  'tab.station': 'Station',
} as const;

export type CopyKey = keyof typeof en;

const fil: Record<CopyKey, string> = {
  'band.offline': 'Offline · nasa phone na ito ang ulat',
  'band.online': 'Online',
  'band.station': 'Istasyon · {name}',
  'band.offline.station': 'Offline · lokal na datos lang',
  'band.online.station': 'Online · na-upload {time}',
  'band.responder': 'Para sa responder · huling sync {time}',
  'band.sim': 'Simulasyon · patunay ng protocol, hindi ng radyo',
  'band.storage': '· halos puno na ang storage',

  'home.count': 'ulat sa phone na ito',
  'home.countEmpty': 'Wala pang laman ang phone na ito',
  'home.urgent': '{n} apurahan',
  'home.last': 'Huling ulat mo',
  'home.rateLimit': '6 na ulat na ngayong oras. Subukan ulit sa {time}.',
  'action.report': 'Mag-ulat',
  'action.report.sub': "Ano'ng nangyayari?",
  'action.passOn': 'Ipasa',
  'action.receive': 'Tumanggap',
  'action.safe': 'Ligtas ako',

  'report.q1': "Ano'ng nangyayari?",
  'report.q2': 'Ilan ang kailangan ng tulong?',
  'report.notSure': 'Hindi sigurado',
  'report.q3': "Ano'ng nakita mo?",
  'report.q3.ph': 'hal. Tubig lampas daan malapit sa kapilya',
  'report.q4': 'Saan?',
  'report.gps.ok': 'Nahanap ang lokasyon',
  'report.gps.none': 'Hindi mahanap ang lokasyon',
  'report.landmark': 'Purok o palatandaan',
  'report.landmark.optional': 'Palatandaan (opsyonal)',
  'report.next': 'Susunod',
  'report.save': 'I-save ang ulat',
  'nav.back': 'Bumalik',

  'cat.MEDICAL': 'Medikal',
  'cat.TRAPPED': 'Na-trap',
  'cat.STRUCTURAL': 'Pinsala',
  'cat.FLOOD': 'Baha',
  'cat.ROAD_BLOCKED': 'Sarado ang daan',
  'cat.MISSING_PERSON': 'Nawawala',
  'cat.WATER_FOOD': 'Tubig at pagkain',
  'cat.SHELTER': 'Matutuluyan',
  'cat.SAFE_CHECKIN': 'Ligtas ako',

  'slip.status.saved': 'Naka-save lang sa phone na ito.',
  'slip.status.passed': 'Naipasa na sa ibang phone.',
  'slip.status.station': 'Umabot na sa istasyon.',
  'slip.status.uploaded': 'Na-upload mula sa phone na ito.',
  'slip.grouped': 'Kasama ng ulat mula sa {n} pang phone.',
  'stamp.saved': 'Naka-save',
  'stamp.passed': 'Naipasa',
  'stamp.station': 'Nasa istasyon',
  'stamp.uploaded': 'Na-upload',
  'stamp.ack': 'Natanggap {time}',
  'stamp.acknowledged': 'Natanggap',
  'stamp.resolved': 'Tapos na',
  'action.passItOn': 'Ipasa',
  'action.done': 'Tapos',

  'pass.title': 'Ipasa',
  'pass.hint': 'Itapat ito sa kabilang phone.',
  'pass.batch': 'Batch {i} ng {n} · {count} ulat',
  'pass.pause': 'Ihinto',
  'pass.resume': 'Ituloy',
  'pass.next': 'Susunod',
  'pass.scanReceipt': 'I-scan ang resibo',
  'pass.swap': 'Magpalit para makuha ang sa kanila.',
  'pass.done': 'Naipasa {n}',
  'pass.empty': 'Walang maipapasa mula sa phone na ito.',
  'recv.aim': 'Itapat sa code nila.',
  'recv.progress': 'Huwag galawin · {i} ng {n}',
  'recv.got': 'Natanggap {n}',
  'recv.new': '{m} bago',
  'recv.showReceipt': 'Ipakita ang resibo',
  'recv.receiptHint': 'Ipa-scan ito sa kanila.',
  'err.cantRead': 'Hindi mabasa. Iiwas sa ilaw.',
  'err.cantRead.2': 'Hindi mabasa. Ilayo nang kaunti ang mga phone.',
  'err.cantRead.3': 'Hindi mabasa. Panatilihin ang code sa loob ng frame.',
  'err.camera': 'Naka-off ang camera para sa PASAbi.',
  'err.openSettings': 'Buksan ang Settings',

  'mine.tab': 'Akin',
  'carrying.tab': 'Dala ko',
  'mine.empty': 'Wala ka pang ulat.',
  'delete.q': 'Burahin sa phone na ito?',
  'delete.body': 'Mananatili ang mga naipasa na.',
  'delete.yes': 'Burahin',
  'delete.no': 'Huwag',
  'undo': 'Ibalik',

  'settings.language': 'Wika',
  'settings.saves': 'Ano ang sine-save ng PASAbi',
  'settings.saves.what': 'Ang iniulat mo',
  'settings.saves.where': 'Lokasyon, kung nahanap',
  'settings.saves.when': 'Oras',
  'settings.saves.noName': 'Hindi ang pangalan mo',
  'settings.saves.noNumber': 'Hindi ang numero mo',
  'settings.saves.noAccount': 'Walang account',
  'settings.station': 'Station mode',
  'pin.wrong': 'Maling PIN',
  'safe.title': 'Ipaalam sa barangay na ligtas ka.',
  'safe.go': 'Mag-check in',

  'ledger.title': 'Sitwasyon',
  'ledger.counts': '{open} bukas · {resolved} tapos na',
  'ledger.lastUpdate': 'Huling update dito',
  'ledger.sort': 'Ayon sa priyoridad',
  'ledger.markSeen': 'Nakita na',
  'ledger.empty': 'Wala pang ulat.',
  'ledger.allOld': 'Lahat dito ay lampas 3 oras na.',
  'mark.new': 'Bago',
  'mark.phone': '+1 phone',
  'mark.people': 'Mas maraming tao',
  'mark.reopened': 'Binuksan muli',
  'fresh.fresh': 'bago',
  'fresh.aging': 'lumilipas',
  'fresh.stale': 'luma',
  'old.note': 'Baka nagbago na.',
  'ev.phones': '{n}\u00A0phone',
  'ev.phone': '1\u00A0phone',
  'ev.reports': '{n}\u00A0ulat',
  'ev.report': '1\u00A0ulat',
  'ev.people': '{n}\u00A0tao',
  'cov.title': 'Saklaw',
  'cov.high': 'Maraming phone',
  'cov.limited': 'Kaunting phone',
  'cov.stale': 'Tahimik mula {time}',
  'cov.none': 'Walang ulat',
  'cov.unnamed': 'Walang pangalang lugar',

  'inc.back': 'Talaan',
  'inc.rank': 'ika-{ordinal} sa {n} bukas',
  'inc.status.open': 'Bukas · hindi pa natatanggap',
  'inc.status.acked': 'Bukas · natanggap',
  'inc.status.resolved': 'Tapos na {time}. Bubuksan muli ng bagong ulat.',
  'inc.phones': 'phone',
  'inc.reports': 'ulat',
  'fact.lastHeard': 'Huling ulat',
  'fact.firstHeard': 'Unang ulat',
  'fact.freshness': 'Kasariwaan',
  'fact.people': 'Tao',
  'fact.people.value': '{n} sa huling ulat',
  'fact.people.none': 'Hindi naiulat',
  'fact.spread': 'Lawak',
  'fact.spread.value': 'Sakop ng {m} m',
  'why.title': 'Bakit ika-{ordinal}?',
  'why.total': 'Kabuuan',
  'gap.nearby': 'May ulat sa malapit',
  'gap.unheard': 'Wala pang ulat tungkol sa',
  'log.title': 'Talaan ng pangyayari',
  'log.reported': 'Nag-ulat si {src}',
  'log.reportedAgain': 'Nag-ulat ulit si {src}',
  'log.received': 'Natanggap sa istasyong ito',
  'log.carriedBy': 'Dinala ni {src}',
  'log.acked': 'Tinanggap dito',
  'log.resolved': 'Tinapos dito',
  'action.ack': 'Tanggapin',
  'action.resolve': 'Tapusin',
  'undo.resolved': 'Tapos na.',

  'station.held': 'ulat na hawak',
  'station.storage': '{n} sa {max}',
  'station.lastUpload': 'Huling upload',
  'station.upload': 'I-upload ngayon',
  'station.needsNet': 'Kailangan ng internet.',
  'station.uploadFailed': 'Hindi na-upload. Nasa phone pa rin.',
  'station.retry': 'Subukan ulit',
  'station.leave': 'Umalis sa station mode',
  'tab.ledger': 'Talaan',
  'tab.station': 'Istasyon',
};

/**
 * Fixed caveats (BR-013, BR-014, BR-017). Screens use these; they never paraphrase them.
 * Show each at most once per screen, in the position given in SCREENS.md.
 */
export const CAVEATS: Record<Lang, { noReport: string; coverage: string; why: string; counts: string }> = {
  en: {
    noReport: "No report doesn't mean none.",
    coverage: "Last 3 hours. No report doesn't mean none.",
    why: 'Sorted by fixed rules. Not a danger rating.',
    counts: 'Counts phones, not people.',
  },
  fil: {
    noReport: 'Walang ulat, hindi ibig sabihing wala.',
    coverage: 'Huling 3 oras. Walang ulat, hindi ibig sabihing wala.',
    why: 'Inayos ayon sa takdang patakaran. Hindi sukat ng panganib.',
    counts: 'Bilang ng phone, hindi ng tao.',
  },
};

const tables: Record<Lang, Record<CopyKey, string>> = { en, fil };

/** t('pass.batch', 'en', { i: 1, n: 2, count: 60 }) → "Batch 1 of 2 · 60 reports" */
export function t(key: CopyKey, lang: Lang, vars?: Record<string, string | number>): string {
  let s = tables[lang][key] ?? en[key];
  if (vars) for (const k of Object.keys(vars)) s = s.split(`{${k}}`).join(String(vars[k]));
  return s;
}

/** Words that must never appear in UI copy (BR-017 + voice rules). Used by the copy check. */
export const BANNED_WORDS = ['successfully', 'please', 'oops', 'verified', 'confirmed', 'severity', 'danger level', 'all clear'] as const;
