import "@fontsource/doto/800.css";
import "@fontsource/doto/900.css";
import "./design/tokens.css";

import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
// A virtual module generated by vite-plugin-pwa at build time.
// eslint-disable-next-line import/no-unresolved
import { registerSW } from "virtual:pwa-register";

import { App } from "./App";
import { restoreLang } from "./design/i18n";
import { offlineReady } from "./hooks";
import { checkLocation } from "./permissions";
import { persisted } from "./screens/Settings";
import { getDeviceId } from "./storage/device";
import { requestPersistence } from "./storage/kv";
import { refreshStore } from "./storage/observations";
import { restoreStation } from "./storage/station";
import { restoreSweeps } from "./storage/sweeps";
import { restoreTransferLog } from "./storage/transferLog";
import { restoreLastUpload } from "./storage/uplink";

async function boot(): Promise<void> {
  try {
    await Promise.all([getDeviceId(), restoreLang(), restoreLastUpload(), restoreTransferLog(), restoreSweeps()]);
    // Station mode first: it sets the store capacity the first write uses.
    await restoreStation();
    await refreshStore();
  } catch {
    // Storage unavailable (e.g. a private tab): the app still opens, and
    // the device ID falls back to one kept in memory for this session.
    await getDeviceId();
  }

  // Say "ready offline" only when a service worker really serves the shell.
  if (navigator.serviceWorker?.controller) offlineReady.set(true);
  // A new build never reloads the page under someone's hands. It is applied
  // when the app goes to the background on a screen with nothing in
  // progress, or else on the next cold launch (the waiting worker takes
  // over once every window of the app is closed).
  let updateWaiting = false;
  const updateSW = registerSW({
    immediate: true,
    onOfflineReady: () => offlineReady.set(true),
    onNeedRefresh: () => {
      updateWaiting = true;
    },
  });
  const SAFE_TO_RELOAD = new Set(["/", "/station", "/mine", "/settings", "/station/status", "/responder"]);
  document.addEventListener("visibilitychange", () => {
    if (updateWaiting && document.visibilityState === "hidden" && SAFE_TO_RELOAD.has(location.pathname)) {
      void updateSW(true);
    }
  });
  void requestPersistence().then((ok) => persisted.set(ok));

  // Startup ask (2026-09-30): location, every launch until on. This learns
  // the current answer; the StartupAsk sheet asks if it is still off.
  void checkLocation();

  createRoot(document.getElementById("root")!).render(
    <StrictMode>
      <App />
    </StrictMode>,
  );
}

void boot();
