import "@fontsource/doto/800.css";
import "@fontsource/doto/900.css";
import "./design/tokens.css";

import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
// A virtual module generated by vite-plugin-pwa at build time.
// eslint-disable-next-line import/no-unresolved
import { registerSW } from "virtual:pwa-register";

import { App } from "./App";
import { restoreLang } from "./design/i18n";
import { offlineReady } from "./hooks";
import { persisted } from "./screens/Settings";
import { getDeviceId } from "./storage/device";
import { requestPersistence } from "./storage/kv";
import { refreshStore } from "./storage/observations";
import { restoreStation } from "./storage/station";
import { restoreLastUpload } from "./storage/uplink";

async function boot(): Promise<void> {
  try {
    await Promise.all([getDeviceId(), restoreLang(), restoreLastUpload()]);
    // Station mode first: it sets the store capacity the first write uses.
    await restoreStation();
    await refreshStore();
  } catch {
    // Storage unavailable (e.g. a private tab): the app still opens, and
    // the device ID falls back to one kept in memory for this session.
    await getDeviceId();
  }

  // Say "ready offline" only when a service worker really serves the shell.
  if (navigator.serviceWorker?.controller) offlineReady.set(true);
  registerSW({ immediate: true, onOfflineReady: () => offlineReady.set(true) });
  void requestPersistence().then((ok) => persisted.set(ok));

  createRoot(document.getElementById("root")!).render(
    <StrictMode>
      <App />
    </StrictMode>,
  );
}

void boot();
